import client from "../PrismaClient/client";

const SKILLS: string[] = [
  "React",
  "Node.js",
  "Python",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "SQL",
  "MongoDB",
  "Express.js",
  "Django",
  "Flask",
  "Java",
  "Spring Boot",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "Android Development",
  "iOS Development",
  "Machine Learning",
  "Data Analysis",
  "Artificial Intelligence",
  "DevOps",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "Blockchain",
  "Solidity",
  "Cybersecurity",
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "Project Management",
  "Agile Methodologies",
  "Scrum",
  "Git",
  "GitHub",
  "Version Control",
  "Testing",
  "Jest",
  "Cypress",
  "Selenium",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "3D Modeling",
  "Blender",
  "Photoshop",
  "Illustrator",
  "Video Editing",
  "Premiere Pro",
  "After Effects",
];

async function seedSkills() {
  await client.skill.createMany({
    data: SKILLS.map((name) => ({ name })),
  });
  console.log("Skills Added to database.");
}
seedSkills();
